#!/usr/bin/env ruby

base_dir = File.dirname(__FILE__)

unless ARGV[0]
  Dir["**/*.tex"].each do |path|
    `cd #{File.dirname(path)} && pdflatex -shell-escape #{File.basename(path)} && cd #{base_dir}`
  end
else
  file = "slides.tex"
  dir = ARGV[0]
  `cd #{dir} && pdflatex -shell-escape #{File.join(file)} && cd #{base_dir}`
end
