#!/usr/bin/env ruby

base_dir = File.expand_path(File.dirname(__FILE__))

unless ARGV[0]
  Dir[File.join(base_dir, "**/*.tex")].each do |path|
    `cd #{File.dirname(path)} && pdflatex -shell-escape #{File.basename(path)}`
  end
else
  file = "slides.tex"
  dir = ARGV[0]
  `cd #{dir} && pdflatex -shell-escape #{File.join(file)}`
end
